server:
  port: ${SERVICE_PORT}
  servlet:
    context-path: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}