spring:
  application:
    name: greeting

server:
#  port: 9007
  contextPath: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true