spring:
  application:
    name: greeting

server:
  port: ${SERVICE_PORT}
  contextPath: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka/
  instance:
    preferIpAddress: true