spring:
  application:
    name: api-1

server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true