version: '2'
services:

  greeting:
    image: mini-cloud/greeting-service:1
    environment:
      SERVICE_PORT: 0
      DISCOVERY_PORT: 8761
      WAIT_FOR_SERVICES: "discovery:8761"
    depends_on:
      - "discovery"

  api-1:
    image: mini-cloud/api-1-service:1
    expose:
      - 9005
    environment:
      SERVICE_PORT: 9005
      DISCOVERY_PORT: 8761
      WAIT_FOR_SERVICES: "discovery:8761"
    depends_on:
      - "greeting"

  api-2:
    image: mini-cloud/api-2-service:1
    expose:
      - 9006
    environment:
      SERVICE_PORT: 9006
      DISCOVERY_PORT: 8761
      WAIT_FOR_SERVICES: "discovery:8761"
    depends_on:
      - "greeting"

  gateway:
    image: mini-cloud/api-gateway-service:1
    ports:
      - "8000:8000"
    environment:
      SERVICE_PORT: 8000
      DISCOVERY_PORT: 8761
      WAIT_FOR_SERVICES: "api-1:9005,api-2:9006"
      CLIENT_ID: e24d11242d2cb0652814
      CLIENT_SECRET: 666ef43d226f3772a0855b69b1c6b31d39bd353a
    depends_on:
      - "api-1"
      - "api-2"

  discovery:
    image: mini-cloud/discovery-server:1
    ports:
      - "8761:8761"
    environment:
      DISCOVERY_PORT: 8761
