spring:
  application:
    name: discovery
  cloud:
    config.discovery.enabled: true

server:
  port: ${DISCOVERY_PORT}

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/