spring:
  application:
    name: api-2

server:
  port: ${SERVICE_PORT}

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true