spring:
  application:
    name: bye

server:
  port: ${SERVICE_PORT}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

security:
  oauth2:
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

logging:
  level:
    org.springframework.security: DEBUG
