spring:
  application:
    name: gateway

encrypt:
  failOnError: false

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka/

ribbon:
  eureka:
    enabled: true

security:
  oauth2:
    client:
      clientId: ${CLIENT_ID}
      clientSecret: ${CLIENT_SECRET}
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

zuul:
  sensitive-headers: Cookie,Set-Cookie

logging:
  level:
    org.springframework.security: DEBUG
