spring:
  application:
    name: gateway

encrypt:
  failOnError: false

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka/

ribbon:
  eureka:
    enabled: true